# Домашнее задание "Продвинутая линейная алгебра".

In [1]:
import numpy as np
from numpy import linalg as LA
from sklearn.decomposition import PCA

## Уровень 0:
#### Придумайте матрицы, которые обладают следующими свойствами (во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!):
* Диагональная, ортогональная, но не единичная(!)

In [2]:
A = np.diag([-1, -1, -1])
A

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [3]:
"""Проверим, является ли матрица оргогональной. 
Ортогональная матрица — квадратная матрица, с вещественными элементами, результат умножения которой 
на транспонированную матрицу, равен единичной матрице."""
AT = A.transpose()
A.dot(AT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

* Верхнетреугольная, ортогональная

In [4]:
B = np.triu([[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
# Проверим, является ли матрица оргогональной.
BT = B.transpose()
B.dot(BT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

* Нижнетреугольная, ортогональная

In [6]:
C = np.tril([[-1, 0, 0],
             [0, 1, 0],
             [0, 0, -1]])
C

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [7]:
# Проверим, является ли матрица оргогональной.
CT = C.transpose()
C.dot(CT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

* Матрица, у которой определитель = 1, и все элементы не равны 0

In [8]:
D = np.array([[2, 1, 1],
             [1, 2, 1],
             [1, 1, 1]])
D

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 1]])

In [9]:
LA.det(D)

1.0

#### Найдите собственные значения и собственные вектора матриц:

In [10]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [11]:
w,v = LA.eig(m)
print('Собственне значения: ', w)
print('Собственне вектора: ',v)

Собственне значения:  [1. 4.]
Собственне вектора:  [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


## Уровень 1:
#### Найдите спектральное разложение матрицы:

In [12]:
m = np.array([[1, 2],
              [2,3]])
print(m)

[[1 2]
 [2 3]]


Спектральное разложение матрицы:

m = St * D * S,где 
* S - ортогональная, 
* D - диагональная из собственных значений X.

In [13]:
# Найдем собственне значения матрицы
w,v = LA.eig(m)
w

array([-0.23606798,  4.23606798])

In [14]:
D = np.diag(w)
D

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [15]:
S = v.T
S

array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])

In [16]:
St = S.transpose()
St

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [17]:
my_m = St @ D @ S
my_m

array([[1., 2.],
       [2., 3.]])